server:
  http_listen_port: 9080
clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml
  
scrape_configs:
  - job_name: classification-service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: classification
          __path__: /app/access.json
    pipeline_stages:
      - json:
          expressions:
            level: levelname
            message: client
            timestamp: asctime